version: '3.9'
services:

  postgres_db:
    image: postgres
    command: -p 6432
    restart: always
    env_file:
      - .env
    expose:
      - 6432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  web:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: taskspark
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8001:8000"
    command: sh -c "chmod +x migrate.sh && sh migrate.sh && sh entrypoint.sh"
  
volumes:
  postgres_data:
